version: '3'

services:

  api:
      build: ./
      image: test_api
      command: uvicorn app:app --workers 1 --host 0.0.0.0 --port 8080
      ports:
        - 8080:8080
      restart: always
      networks:
        my-network:
          aliases:
          - fast-api
        
     


  nginx-proxy:
      image: nginx:alpine

      ports:
        - "80:80"
      depends_on:
        - api
      volumes:
        - ./data/nginx/app.conf:/etc/nginx/conf.d/default.conf
        - certbot-etc:/etc/letsencrypt
        - certbot-var:/var/lib/letsencrypt
      networks:
        - my-network


  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt

    depends_on:
      - api
    command: certonly  --email example@your_domain --agree-tos --no-eff-email --staging -d your_domain  -d www.your_domain #make your custom change


networks:
    my-network:
      driver: bridge


volumes:
  certbot-etc:
  certbot-var:
      
      
    
