version: '3'

services:

  api:
    build: ./
    image: test_api
    command: uvicorn app:app --workers 1 --host 0.0.0.0 --port 8080
    ports:
      - 8080:8080
    restart: always


  nginx-proxy:
    image: nginx:alpine
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./data/nginx/app.conf:/etc/nginx/conf.d/default.conf

  # certbot:
  #   image: certbot/certbot
