version: '3'

services:

  api:
      build: ./
      image: test_api
      command: uvicorn app:app --workers 1 --host 0.0.0.0 --port 8080
      ports:
        - 8080:8080
      restart: always
      networks:
        my-network:
          aliases:
          - fast-api
        
     


  nginx-proxy:
      image: nginx:alpine

      ports:
        - "80:80"
      depends_on:
        - api
      volumes:
        - ./data/nginx/app.conf:/etc/nginx/conf.d/default.conf
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot

      networks:
        - my-network


  certbot:
      image: certbot/certbot
      container_name: certbot
      volumes:
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot   

      depends_on:
        - api
      command: certonly --webroot -w /var/www/certbot --force-renewal --email {email} -d {domain} --agree-tos


networks:
    my-network:
      driver: bridge


      
      
    
